<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3'; import { ref } from 'vue';
interface Item { slug:string; title:string; subtitle:string|null; description:string|null; valueCents:number|null; date:string|null }
const props=defineProps<{kind:'contracts'|'procurements'|'suppliers';title:string;query:string;items:Item[]}>(); const q=ref(props.query);
const indexRoute=()=>route(`${props.kind}.index`); const showRoute=(slug:string)=>route(`${props.kind}.show`,slug);
const submit=()=>router.get(indexRoute(),{q:q.value},{preserveState:true,replace:true});
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
</script>
<template><Head :title="title"/><div class="min-h-screen bg-stone-50 text-slate-950"><header class="border-b bg-white"><div class="mx-auto flex max-w-5xl justify-between px-5 py-5"><Link :href="route('home')" class="text-xl font-black">Acorda <span class="text-teal-700">Alcobaça</span></Link><nav class="flex gap-4 text-sm font-bold"><Link :href="route('contracts.index')">Contratos</Link><Link :href="route('procurements.index')">Licitações</Link><Link :href="route('suppliers.index')">Fornecedores</Link></nav></div></header><main class="mx-auto max-w-5xl px-5 py-12"><p class="text-sm font-black uppercase tracking-widest text-teal-700">Compras públicas</p><h1 class="mt-3 text-4xl font-black">{{ title }}</h1><p class="mt-4 text-slate-600">Dados preservados da fonte oficial. Ausência de resultado não comprova inexistência.</p><form class="mt-7 flex gap-3" @submit.prevent="submit"><input v-model="q" type="search" :placeholder="kind==='suppliers'?'Nome do fornecedor':'Número, objeto ou participante'" class="min-w-0 flex-1 rounded border p-3"/><button class="rounded bg-teal-700 px-5 font-bold text-white">Buscar</button></form><p v-if="kind==='suppliers' && query.length<2" class="mt-8 border-l-4 border-amber-400 bg-white p-4">Digite ao menos dois caracteres para buscar fornecedores.</p><ul v-else class="mt-8 grid gap-4"><li v-for="item in items" :key="item.slug" class="border bg-white p-5"><Link :href="showRoute(item.slug)" class="text-xl font-black text-teal-800 underline">{{ item.title }}</Link><p v-if="item.subtitle" class="mt-2 font-semibold">{{ item.subtitle }}</p><p v-if="item.description" class="mt-2 line-clamp-2 text-sm text-slate-600">{{ item.description }}</p><div class="mt-3 flex gap-5 text-sm"><strong v-if="item.valueCents!==null">{{ money(item.valueCents) }}</strong><span v-if="item.date">{{ item.date }}</span></div></li></ul></main></div></template>
